version: '3'

services:
  sandbox:
    image: dorowu/ubuntu-desktop-lxde-vnc:bionic-lxqt
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./shared:/home/sandbox/shared
    ports:
      # VNC GUI client port
      - 5900:5900
      # Web GUI client port
      - 6080:80
    environment:
      - VNC_PASSWORD=white!=black
      - HTTP_PASSWORD=white!=black
      - USER=sandbox
      - PASSWORD=white!=black

# RUN SCRIPT:
# docker-compose up -d